### ISSUE TITLE
Selecting attribute with name "value" in a query results in memory exhaustion

### ISSUE THREAD

**Issue by OptimusCrime** [modxcms/xpdo#108]
### Summary
Simple query results in a fatal error

### Step to reproduce
Query below is ran i a snippet. 

Note that I have also tried all combinations with or without ticks around `value` but the error is still there. It just happens on the `value` attribute. The rest of the attributes are fetched without problem. 

Also note that I've tried with the other syntaxes (array and getselectcolumns) with the same results.

```
$c = $modx->newQuery('modTemplateVarResource');
$c->select('modTemplateVarResource.value');
$collection = $modx->getCollection('modTemplateVarResource', $c);
```

### Observed behavior
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /core/xpdo/om/xpdoobject.class.php on line 1876

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

Also note that the resulting query is in fact correct. The problem occur when I run `getCollection`. `getObject` works fine.

### Expected behavior
No errors.

### Environment
MODX Revo 2.5.4-pl

**Comment by pashajanx** [comment]
Have you solved the problem?

**Comment by OptimusCrime** [comment]
@pashajanx Hello. No, this issue was never resolved. Have you experienced it yourself?

**Comment by Mark-H** [comment]
I'm gonna assume four years down the line this is no longer relevant? 😬 

My best guess is that's failing because there's a ton of objects being loaded into memory, rather than anything to do with the value. Even when you only select the value, each modTemplateVarResource object will be initialized into memory.

What may have also happened is that because you only load the value, and not the primary key (id), that it gets thrown into a loop trying to lazy load the part of the object it needs to lazy load the rest of the object. Selecting both the ID and the value would fix that, or alternatively you can bypass object creation by running it as a PDO query instead of a xPDO getCollection.
